### ISSUE TITLE
在二分类下，当文本数量达到百万级时，会在某一时刻正确率会突然下降50%左右

### ISSUE THREAD

**Issue by WavesLi** [649453932/Bert-Chinese-Text-Classification-Pytorch#108]
在二分类下，batch_size=10,当文本数量达到百万级时，会在某一时刻正确率会突然下降50%左右，就像是模型突然变成了随机的，在小数据集上没有问题。无论是用bert.py 还是ERNIE.py
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/33248674/132792996-9d205641-0b5f-4b86-acee-90743588b2cd.png">

**Comment by 649453932** [comment]
> 在二分类下，batch_size=10,当文本数量达到百万级时，会在某一时刻正确率会突然下降50%左右，就像是模型突然变成了随机的，在小数据集上没有问题。无论是用bert.py 还是ERNIE.py
> <img alt="image" width="1175" src="https://user-images.githubusercontent.com/33248674/132792996-9d205641-0b5f-4b86-acee-90743588b2cd.png">


学习率太大了，也可以加个学习率衰减

**Comment by WavesLi** [comment]
> > 在二分类下，batch_size=10,当文本数量达到百万级时，会在某一时刻正确率会突然下降50%左右，就像是模型突然变成了随机的，在小数据集上没有问题。无论是用bert.py 还是ERNIE.py
> > <img alt="image" width="1175" src="https://user-images.githubusercontent.com/33248674/132792996-9d205641-0b5f-4b86-acee-90743588b2cd.png">
> 
> 学习率太大了，也可以加个学习率衰减

> 抱歉哈，我最后通过两种方式解决的了这个问题，一个方式是直接采用Adam而不是用代码中的优化器，但是正确率下降了4个点，另一种方式就是屏蔽代码中的优化warmup参数和t_total参数解决了这个问题。我通过经验也只是觉得是学习率的问题，查看了下warnup的机制我觉得是在小batch下不适用。你要是有新的想法欢迎讨论
