### ISSUE TITLE
使用纯bert，准确率一直在50%左右，没有提升？

### ISSUE THREAD

**Issue by yuanfengning** [649453932/Bert-Chinese-Text-Classification-Pytorch#134]

**Comment by yuanfengning** [comment]
在下载vocab.txt时，自己新建了一个txt,把数据拷进去了，也没有报错，就是准确率上不去，把文件另存为就没问题了。

**Comment by Gavingx** [comment]
> 在下载vocab.txt时，自己新建了一个txt,把数据拷进去了，也没有报错，就是准确率上不去，把文件另存为就没问题了。

一摸一样，我也是新建了一个vocab.txt，把词表复制进去，一直50%左右，下载不新建就正常
