### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'THUCNews/saved_dict/bert.ckpt'

### ISSUE THREAD

**Issue by ChaunceyBai98** [649453932/Bert-Chinese-Text-Classification-Pytorch#14]
没看到这个文件啊

**Comment by ChaunceyBai98** [comment]
我好像知道了

**Comment by ChaunceyBai98** [comment]
不，我还是找不到

**Comment by ChaunceyBai98** [comment]
好的，我真的找到了

**Comment by aimasa** [comment]
所以怎么找到的啊？

**Comment by ChaunceyBai98** [comment]
去学习一下Bert的官方网页你就知道了。

**Comment by aimasa** [comment]
奥，明白了，谢谢啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chauncey Bai"<notifications@github.com&gt;; 
发送时间: 2019年11月8日(星期五) 下午2:40
收件人: "649453932/Bert-Chinese-Text-Classification-Pytorch"<Bert-Chinese-Text-Classification-Pytorch@noreply.github.com&gt;; 
抄送: "no one knows who am i"<794182811@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [649453932/Bert-Chinese-Text-Classification-Pytorch] FileNotFoundError: [Errno 2] No such file or directory: &#39;THUCNews/saved_dict/bert.ckpt&#39; (#14)




去学习一下Bert的官方网页你就知道了。

**Comment by CCChenhao997** [comment]
我是直接在THUCNews下新建了一个saved_dict文件
