### ISSUE TITLE
报错：RuntimeError: Parent directory THUCNews/saved_dict does not exist

### ISSUE THREAD

**Issue by nonoback1** [649453932/Bert-Chinese-Text-Classification-Pytorch#169]
我是一个来自建筑施工行业的小白，希望各位大佬不吝赐教、答疑解惑。

我通过CMD输入python run.py --model ERNIE后，显示Loading data，然后到了Epoch（1/3），报错：“RuntimeError: Parent directory THUCNews/saved_dict does not exist”。前期我已经把THUCNews下载下来了，但是没有找到saved_dict

请问：
1、我的运行方式对吗？
2、哪里能够搞到saved_dict？

**Comment by WronZrald** [comment]
我也遇到这个问题了，请问你解决了吗

**Comment by WronZrald** [comment]
> 我是一个来自建筑施工行业的小白，希望各位大佬不吝赐教、答疑解惑。
> 
> 我通过CMD输入python run.py --model ERNIE后，显示Loading data，然后到了Epoch（1/3），报错：“RuntimeError: Parent directory THUCNews/saved_dict does not exist”。前期我已经把THUCNews下载下来了，但是没有找到saved_dict
> 
> 请问： 1、我的运行方式对吗？ 2、哪里能够搞到saved_dict？

我也遇到这个问题了，请问你解决了吗

**Comment by Conqueror712** [comment]
> > 我是一个来自建筑施工行业的小白，希望各位大佬不吝赐教、答疑解惑。
> > 我通过CMD输入python run.py --model ERNIE后，显示Loading data，然后到了Epoch（1/3），报错：“RuntimeError: Parent directory THUCNews/saved_dict does not exist”。前期我已经把THUCNews下载下来了，但是没有找到saved_dict
> > 请问： 1、我的运行方式对吗？ 2、哪里能够搞到saved_dict？
> 
> 我也遇到这个问题了，请问你解决了吗

Answer: 在对应目录下自己创建一个saved_dict文件夹，即可
