### ISSUE TITLE
求大佬帮助一下，项目架构问题

### ISSUE THREAD

**Issue by zlhcsm** [649453932/Bert-Chinese-Text-Classification-Pytorch#30]
大佬，作为一个新人，对于代码的理解力还不是么强！所以相结合博客来学习一下！比如：项目中的BERT+CNN进行训练，那么此处的CNN是不是TextCNN那一套？BERT最终训练出来的是字向量还是句子向量？而且模型的整体输入流输出流是什么！还希望能帮忙解答一下谢谢

**Comment by 649453932** [comment]
先打好基础吧，bert这些原理得自己去看啊
