### ISSUE TITLE
单机多GPU运行

### ISSUE THREAD

**Issue by lidianxiang** [649453932/Bert-Chinese-Text-Classification-Pytorch#42]
我想在单机上使用多个GPU来训练，在run.py文件的最开始加上了
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "4,5,6,7"
并且注释掉了
np.random.seed(1)
torch.manual_seed(1)
torch.cuda.manual_seed_all(1)
torch.backends.cudnn.deterministic = True 
但是还是只使用的GPU:4这一个GPU

这条语句在tensorflow中可以正常运行的，但是在pytroch中为什么会失效了呢？
在线求解～

**Comment by lidianxiang** [comment]
解决了。具体步骤参考这篇文章：https://wnwhite.xin/2019/11/11/pytorch_multi_gpu/，知乎上的关于多卡运行的，都只说了一半。累屁了～

**Comment by Wanjun0511** [comment]
@lidianxiang  链接打不开了，能给个新链接吗？多谢了

**Comment by dujiajianbing** [comment]
> 

t同求
