### ISSUE TITLE
 No such file or directory: './bert_pretrain\\bert_config.json'

### ISSUE THREAD

**Issue by HelloF1sh** [649453932/Bert-Chinese-Text-Classification-Pytorch#47]
我感觉是我的在文件夹bert_pretrain中放的东西不对，README中写了要放：
pytorch_model.bin
bert_config.json
vocab.txt
我下载了链接中的bert-base-chiness并直接解压到了bert_pretrain文件夹中，但是没有看到要求中的文件。

**Comment by Triver-ac** [comment]
你好，请问你的问题解决了吗？我也遇到同样的问题，初学者表示好难呜呜呜
