### ISSUE TITLE
CUDA out of memory 

### ISSUE THREAD

**Issue by MambaMelon** [649453932/Bert-Chinese-Text-Classification-Pytorch#6]
您好，请问下您，跑ERNIE模型时，报CUDA out of memory的错误。我的显卡是1050 Ti

**Comment by MambaMelon** [comment]
还想请教一下，你的博客地址在哪里啊？可否贴一下

**Comment by kingsea0-0** [comment]
您好，请问您的问题解决了吗。我也是跑ERNIE时，开始正常，在第二个epoch就out of memory了，但是换到小数据集就没问题。

**Comment by Spr1nt0a0** [comment]
可以调小batchsize或者padsize

**Comment by kingsea0-0** [comment]
已经解决了。如果是batchsize过大应该一开始就跑不起来，这个代码训练过程中有中间变量没有释放，随着迭代次数增加占用显存越来越大，导致显存后期不够用了。

**Comment by dabao0903** [comment]
同样的问题，执行bert 修改了pad_size，报错CUDA out of memory，但并不是内存的问题

**Comment by moluchase** [comment]
> 同样的问题，执行bert 修改了pad_size，报错CUDA out of memory，好像是模型导入pretrained时候，出错了，有遇到的朋友请解答下疑惑，谢谢~

请问，该问题解决了吗

**Comment by wangjs9** [comment]
可以更改config中batch_size的

**Comment by dabao0903** [comment]
> 可以更改config中batch_size的

应该不是这个问题，试过batch_size=1，也会报错

**Comment by moluchase** [comment]
> > 可以更改config中batch_size的
> 
> 应该不是这个问题，试过batch_size=1，也会报错

是这个问题，我已经试过了，修改batch_size或者修改pad_size

**Comment by limo1995** [comment]
你显存不够吧

**Comment by xu-cpp** [comment]
试试在run.py里加上这两行代码
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '2, 3'
