### ISSUE TITLE
Model name './bert_pretrain' was not found in model name list

### ISSUE THREAD

**Issue by zyqdragon** [649453932/Bert-Chinese-Text-Classification-Pytorch#65]
Model name './bert_pretrain' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed './bert_pretrain/vocab.txt' was a path or url but couldn't find any file associated to this path or url.

**Comment by HQ-LV** [comment]
I also met this problem. How did you solve it? thank you！
