### ISSUE TITLE
This overload of add_ is deprecated

### ISSUE THREAD

**Issue by cfy42584125** [649453932/Bert-Chinese-Text-Classification-Pytorch#95]
![image](https://user-images.githubusercontent.com/62530854/123212212-1472a380-d4f7-11eb-8d2a-d31447f5606f.png)

D:\Bert-Chinese-Text-Classification-Pytorch\pytorch_pretrained\optimization.py:275: UserWarning: This overload of add_ is deprecated:
	add_(Number alpha, Tensor other)
Consider using one of the following signatures instead:
	add_(Tensor other, *, Number alpha) (Triggered internally at  ..\torch\csrc\utils\python_arg_parser.cpp:1025.)
  next_m.mul_(beta1).add_(1 - beta1, grad)

**Comment by yuanfengning** [comment]
pytorch版本不对
