### ISSUE TITLE
请问 已经安装numpy的情况下，仍报错“ ModuleNotFoundError: No module named 'numpy' ”，如何处理

### ISSUE THREAD

**Issue by jiangxqing** [649453932/Bert-Chinese-Text-Classification-Pytorch#99]
试了各种办法都没法解决，求大佬帮忙解答，感激不尽！
![image](https://user-images.githubusercontent.com/57859622/125163868-c1207680-e1c1-11eb-916e-8385545f4bd5.png)

**Comment by YjhCS** [comment]
应该是安装在了不同的环境中，卸载后重新装，有的是装在了python环境里，有的是anaconda环境。
